export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const GET_USER_PAGINATION = "GET_USER_PAGINATION";
export const GET_USER_PAGINATION_WITH_SEARCH =
  "GET_USER_PAGINATION_WITH_SEARCH";
export const GET_USER_ID = "GET_USER_ID";
export const CURRENT_PAGE_PAGINATION = "CURRENT_PAGE_PAGINATION";
export const GET_ALL_NAME_USER = "GET_ALL_NAME_USER";
